### ISSUE TITLE
api document

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#206]
@kelvin-wong can you provide or generate a document like `OpenAPI` for `api-dispute` and `api-evidence`? It would be useful to do the e2e testing, thanks!

**Comment by kelvin-wong** [comment]
@apolkingg8 I have added API doc links in dev mode, you may provision your skaffold again. The dispute and evidence API doc links will be `http://localhost:3000/docs` and `http://localhost:3010/docs` respectively.

**Comment by solomondefi-dev** [comment]
Thanks!

**Comment by apolkingg8** [comment]
I'll reopen this because the doc is unuseable. For `http://localhost:3000/docs`, the param of `POST /api/events` is "No parameters". And `http://localhost:3010/docs` returns `{"detail":"Not Found"}`. @solomondefi-dev please check it.

**Comment by beefho67** [comment]
@solomondefi-dev @apolkingg8 This is blocking #161. Anything I can help with / work on the issue after I am back from Chinese New Year break?

**Comment by solomondefi-dev** [comment]
@[apolkingg8](https://github.com/apolkingg8) It's non-trivial to automatically create API docs for this endpoint, since it's based on the generated events and is not using a standard Dto model. I will see if there is any workaround, but you can take a look at the tests written for the endpoint, the data is near the bottom of the file: `apps/api-dispute/src/app/tests/test_api.py`

**Comment by apolkingg8** [comment]
> @[apolkingg8](https://github.com/apolkingg8) It's non-trivial to automatically create API docs for this endpoint, since it's based on the generated events and is not using a standard Dto model. I will see if there is any workaround, but you can take a look at the tests written for the endpoint, the data is near the bottom of the file: `apps/api-dispute/src/app/tests/test_api.py`

I already checked the py test file. Unfortunately, it's not enough to describe the API design, that's why I create this issue. A document is necessary to let somebody co-work on this.

**Comment by solomondefi-dev** [comment]
What exactly do you need? I can generate `curl` commands from the py test file if that helps. Can you explain more about why it's not enough to proceed?

**Comment by apolkingg8** [comment]
I'm implementing functional tests in https://github.com/SolomonDefi/solomon-monorepo/blob/161_deploy-contract/apps/app-e2e/src/api-dispute.spec.ts . I want to make sure I tested all the cases, so I need the correct spec. If you think the current implementation is enough, that's fine.

**Comment by solomondefi-dev** [comment]
It's enough to match the events in `test_api.py` for now. There definitely should be API documentation, but it's not a quick fix, since from what I can tell we can't easily use the python framework's built in doc generation.

Another way we can solve it is by generating contract documentation from the Solidity files. This will contain the events, though it will not include `type` directly (e.g. `"type": "dispute.preorder.created"`).

**Comment by solomondefi-dev** [comment]
Latest PR should resolve this, if not please re-open @apolkingg8
