### ISSUE TITLE
Add evidence uploader frontend Dockerfile

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#21]
Add Dockerfile  for evidence uploader frontend. Example template:

```
# BASE IMAGE (37.4MB)
# ------------------------------------------------------------------------------------
FROM alpine:3.14.1 AS base
ARG NODEJS_VER=14
ENV NODEJS_VER=$NODEJS_VER
ARG NPM_VER=7
ENV NPM_VER=$NPM_VER
ARG TINI_VER=0.19
ENV TINI_VER=$TINI_VER

RUN apk add --no-cache nodejs~="$NODEJS_VER" tini~="$TINI_VER"
RUN addgroup -g 1001 -S app && adduser -u 1001 -S app -G app

# DEV APP IMAGE (? MB)
# ------------------------------------------------------------------------------------
FROM base as dev
ENV SHELL=/bin/sh
RUN apk add --no-cache \
  curl~=7.78 \
  npm~="$NPM_VER"
WORKDIR /usr/src
# RUN npm install -g install-subset
# COPY subset.config.js ./
COPY package.json ./
COPY package-lock.json ./
# RUN subset install web-dev --all
RUN npm install
COPY workspace.json ./
COPY nx.json ./
COPY tsconfig*.json ./
COPY libs/web ./libs/web
# COPY libs/shared ./libs/shared
COPY apps/web/tsconfig*.json ./apps/web/
COPY apps/web/index.html ./apps/web/
COPY apps/web/vite.config.ts ./apps/web/
COPY apps/web/postcss.config.js ./apps/web/
COPY apps/web/src ./apps/web/src
ENTRYPOINT ["/sbin/tini", "-v", "--"]
CMD ["npx", "nx", "serve", "web"]
```

Subset config left out until it's implemented.

**Comment by beefho67** [comment]
Should this Dockerfile be placed under https://github.com/SolomonDefi/solomon-monorepo/tree/main/apps/web-evidence   ?

**Comment by solomondefi-dev** [comment]
Yes 👍

**Comment by beefho67** [comment]
Dockerfile can be built from the root level of monorepo by

`docker build --progress=plain --no-cache --tag web-evidence:dev -f apps/web-evidence/Dockerfile --target=web_evidence_dev --label web-evidence .`

and can be run successfully by

`docker run -p 8000:8000 <image_id>`

It's very likely that we build the image several time based on what's changed in subset.config.js. We need to clean up previous images. Before cleaning up images, make sure to delete all old containers by

`docker rm <container_id>`

Since the image is labelled, it's very useful to clean up old images by

`docker image prune --force --filter='label=web-evidence'`

**Comment by solomondefi-dev** [comment]
Sounds good! With the skaffold integration I will also add an `npm run prune` script that prunes all images.

**Comment by beefho67** [comment]
Hi @solomondefi-dev,

Should I add building this docker image as one of the CI check steps in https://github.com/SolomonDefi/solomon-monorepo/blob/main/.github/workflows/pr-commit.yaml?

Thanks

**Comment by solomondefi-dev** [comment]
That's ok, I can add it together with the skaffold work
