### ISSUE TITLE
Platform fees

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#89]
Implement platform fee dispersal. There is a TODO in `SlmShared.sol` for where this should occur.

1. A percentage of transactions goes to the juror/judge contract for platform participation rewards. This is possible to update via the contract owner (or possible future defi mechanism)
2. A percentage of transactions goes to the owner/admin for platform upkeep and maintenance costs.

- Percentages have a possible resolution of 3 decimal places
- For now, defaults are 1.5% to jurors and 0.5% for upkeep

**Comment by beefho67** [comment]
- thinking about 0.5% upkeep fee for platform maintenance
- 1.5 % goes to voters
- Waiting for the response from the community

**Comment by jtse0** [comment]
in reference to the conversation from issue #165 relating to discounts, it might be more appropriate to continue the discussion here since it pertains to reductions in the platform transaction fees.  Perhaps we can clarify here the percentage that we want to use for the discounts related to using SLM in transactions.  We can take note of anything else related to the discounts here as well.
